# Print out all recipes when running `just`
_default:
    @just --list

# Variables
whiskers_cmd := "cargo run --bin whiskers --"

# Generate a single file containing all four flavors
gen:
  @{{whiskers_cmd}} input.tera
