name: Lint

on:
  pull_request:
    paths: ["**.rs", "**.toml", "**.lock"]
  push:
    branches: [main]
    paths: ["**.rs", "**.toml", "**.lock"]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-unknown-unknown"
          components: "rustfmt,clippy"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}-lint

      - name: clippy
        run: |
          cargo clippy
          cargo clippy --target wasm32-unknown-unknown --lib
          cargo clippy --target wasm32-unknown-unknown --lib --all-features

      - name: rustfmt check
        run: |
          cargo fmt --all --check
