name: Test

on:
  pull_request:
    paths: ["**.rs", "**.toml", "**.lock"]
  push:
    branches: [main]
    paths: ["**.rs", "**.toml", "**.lock"]

jobs:
  rust:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}-test

      - name: cargo test
        run: cargo test --all-features
